### PR TITLE
Push event added for Bitbucket cloud

### PR DESCRIPTION
**Pull request by Nisarg10**

### CODE REVIEW

**Comment by cvitter** [comment]
@Nisarg10 have you attempted this since the following PR was mereged: https://github.com/cvitter/mattermost-bitbucket-bridge/pull/10?

I don't have bitbucket cloud but support was added and others are using it.

**Comment by Nisarg10** [comment]
Yes, I have attempted it and it was sending empty messages. 

image

**Comment by mikeehun** [comment]
Thanks for the code @Nisarg10, it works perfect after you add:
`import datetime` :)

**Comment by Nisarg10** [comment]
@mikeehun Thanks for the fix.

**Comment by cvitter** [comment]
@mikeehun and @Nisarg10 - Can you confirm which PRs should be merged? I no longer have a cluster to test on.

**Comment by Nisarg10** [comment]
**PR #13 should be merged** as it contains both @Nisarg10 and @mikeehun work. PR #12 is missing one import sentence.

**Pull request merged**
